### ISSUE TITLE
demo环境登录不进去

### ISSUE THREAD

**Issue by HiTigerXu** [adorabled4/hxBI#8]
![image](https://github.com/adorabled4/hxBI/assets/20093698/5d529c59-2758-41f9-a9dd-826099bbe7e4)

**Comment by adorabled4** [comment]
非常抱歉，测试的服务器性能有限 ，后端和相关的服务我暂时关闭掉了，目前前端的静态页面还在Nginx ，所以页面是可以访问的，但是接口无法访问
